functional:  
 - Пользователь должен иметь возможность искать товары по ключевому слову или категории
 - Пользователь должен иметь возможность фильтровать товары
 - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
 - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
 - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
 - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
 - Сайт должен быть безопасным и защищать данные пользователя
 - Сайт должен иметь мобильную версию
 - Сайт нужно протестировать на совместимость с последними версиями браузеров
 - Важно, чтобы сайт мог обрабатывать большое количество трафика
 - Сайт должен быть доступен на различных устройствах
 - Сайт должен иметь локализацию (перевод) на русский и английский языки
 - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
 - При обновлении страницы авторизованный пользователь должено сохранять статус авторизации
 - При обновлении страницы добавленные товары в корзине не должны исчезать 
 - При обновлении страницы корзины товары, добавленные в корзину, должны сохраняться.
 - Примененные фильтры при переходах между страницами должны сохраняться   
 - Пользователь должен иметь возможность удалить любой товар из корзины
